### ISSUE TITLE
HTV-2 simulations

### ISSUE THREAD

**Issue by MarcoFossati** [FASTT/SU2#14]
- [x] Convert existing mesh in SU2 format
 - [x] Define flight conditions (up to 3)
 - [x] Run with AUSM at constant Cp
    - [x] Mach 7
    - [x] Mach 10
 - [ ] Run with BGK at variable Cp
    - [ ] Mach 7
    - [ ] Mach 10

**Comment by alexmogavero** [comment]
I realised that in the second order M7 case, restarted from 1st order, I did not select the limiter, that is why it exploded. I have now corrected that and it is running, fingers crossed!

**Comment by alexmogavero** [comment]
AUSM Mach 10 is the only one in which I monitored the forces, according to the forces the simulation is not fully converges, but for now I consider it done.

**Comment by alexmogavero** [comment]
After continuation of Navier Stokes runs the forces are still not converged.
![image](https://user-images.githubusercontent.com/12628463/31654163-0ccd5706-b31d-11e7-8350-42f20acf026b.png)
It seems they are slowly evolving. I guess the same thing is happening for the BGK cases only there it is not visible because there are not enough iterations (and there will never be).
At this pace we will never reach full convergence, so from my point of view we have just to decide when we have enough.

**Comment by alexmogavero** [comment]
I think I understand why the lift flips from negative to positive. Unfortunately as usual the answer is again convergence.
I have analysed the results of constant Cp at the point where we switched to variable Cp and the lift was negative. Then going further with the iterations it changed to positive. The variable Cp cases however did only few thousands of iterations so the value staid negative.
See below:

```
	A=	1.98504	q_inf =	16612.472690286	
					
M7					
   iteration	Drag 	Lift	        CD	                 CL
VarCP	228143	256.806	-3.78157	0.0077875639	-0.000114675
ConCP	226421	252.87	-11.5744	0.0076682059	-0.0003509902
ConCP	331699	267.068	 6.82754	0.0080987559	0.0002070431
					
M10					
      iterations  Drag	Lift	        CD	                 CL
VarCP	192287	297.379	-3.80177	0.0090179278	-0.0001152875
ConCP	190942	291.672	-18.0632	0.0088448648	-0.0005477611
ConCP	279900	319.275	 14.9763	0.0096819174	0.0004541517
```

now we have to decide how to proceed. As I said before the constant Cp cases, albeit more iterations, they cannot be considered converged (see history of forces). Variable Cp ones are however even further away from convergence and they will never reach the number of iterations reached by the consta Cp ones, since BGK is too slow.
Therefore for me the only feasible solution is to put in the report all the results at the same level of convergence, so neglecting the restarted constant Cp ones. 
So my call is to stop here and focus on other more important runs, but @MarcoFossati let me know what you think.

**Comment by MarcoFossati** [comment]
Let's try to do something about it, I am boarding now and can discuss tomorrow

M

_____________________________________________________________________
Marco Fossati, PhD
Lecturer in Computational Aerodynamics

Laboratory for Future Air-Space Transportation Technology
Aerospace Centre of Excellence
Department of Mechanical and Aerospace Engineering
University of Strathclyde, 75 Montrose Street, Glasgow, G1 1XJ

phone: +44 (0)141-574-5061
web: www.strath.ac.uk/fastt<http://www.strath.ac.uk/fastt>

On 23 Oct 2017, at 12:38 PM, Alessandro Mogavero <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I understand why the lift flips from negative to positive. Unfortunately as usual the answer is again convergence.
I have analysed the results of constant Cp at the point where we switched to variable Cp and the lift was negative. Then going further with the iterations it changed to positive. The variable Cp cases however did only few thousands of iterations so the value staid negative.
See below:

        A=      1.98504 q_inf = 16612.472690286

M7
   iteration    Drag    Lift            CD                       CL
VarCP   228143  256.806 -3.78157        0.0077875639    -0.000114675
ConCP   226421  252.87  -11.5744        0.0076682059    -0.0003509902
ConCP   331699  267.068  6.82754        0.0080987559    0.0002070431

M10
      iterations  Drag  Lift            CD                       CL
VarCP   192287  297.379 -3.80177        0.0090179278    -0.0001152875
ConCP   190942  291.672 -18.0632        0.0088448648    -0.0005477611
ConCP   279900  319.275  14.9763        0.0096819174    0.0004541517


now we have to decide how to proceed. As I said before the constant Cp cases, albeit more iterations, they cannot be considered converged (see history of forces). Variable Cp ones are however even further away from convergence and they will never reach the number of iterations reached by the consta Cp ones, since BGK is too slow.
Therefore for me the only feasible solution is to put in the report all the results at the same level of convergence, so neglecting the restarted constant Cp ones.
So my call is to stop here and focus on other more important runs, but @MarcoFossati<https://github.com/marcofossati> let me know what you think.
