### ISSUE TITLE
Implement strong form of BC

### ISSUE THREAD

**Issue by MarcoFossati** [FASTT/SU2#5]
- [x] Strong form for temperature at the wall (isothermal BC has to be enforced in a proper manner)
- [x] Strong form for Euler/Symmetry BC (normal component to the velocity to the wall)
- [x] To add a switch in configuration file that makes possible going back to weak BC
- Verify this implementation with ROE on:
   - [ ] Flat plate
   - [ ] Delta wing
   - [ ] Torus

**Comment by MarcoFossati** [comment]
We should follow the same formulation used in SU2 for the viscous wall (no-slip) BC

**Comment by alexmogavero** [comment]
I think the shock tube simulation was not converged. I re-launched the ROE 2nd order and it is changing. Not for the best however.
![image](https://user-images.githubusercontent.com/12628463/28416175-c56b85d0-6d4a-11e7-8e7a-543083f6b898.png)

**Comment by alexmogavero** [comment]
This issue is closed. However the strong BC could be implemented with a much less convoluted way that does not need to set explicitly the residuals so to do not change some boundary parameters.
A flag could be defined in the `Cvariable` class that switch on/off the holding of the velocity or the temperature, then the actual holding of these parameters could be implemented in the method `bool CVariable::SetPrimVar (CFluidModel *, FluidModel)` that is called at the beginning of each iteration.

However this implementation seems to work, so for now I close the issue.

**Comment by MarcoFossati** [comment]
The validation of the strong form of BC is not going well. Over the three test cases we have to consider none is converging properly. While for the delta and the torus I attribute this to the mesh, for the flat plate the problem should be in the method itself that does not work well with the rest of the framework (tried with different CFLs, different methods, etc.). The temperature at the wall is indeed constant, but along the plane of symmetry heavy oscillations arise and overall the convergence is not good. I have to put this on hold for the moment since it is taking too much time. I will try to see what happens with better meshes in the case of the torus and the delta wing BUT with weak BCs.
